# Generated by Django 3.1.3 on 2021-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210531_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
