# Generated by Django 3.1.3 on 2021-06-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210601_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created']},
        ),
    ]
